# Generated by Django 3.0.8 on 2020-07-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200726_1946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'followed_user')},
        ),
    ]
